/**
 * Cross-compatibility tests for lib/jwt.ts (Node.js) and lib/auth/jwt-edge.ts (Edge / Web Crypto)
 *
 * The authentication system uses two distinct JWT implementations that must interoperate:
 *
 *   - lib/jwt.ts         — uses `jsonwebtoken` (Node.js runtime, runs in API routes)
 *   - lib/auth/jwt-edge.ts — uses `crypto.subtle` (Web Crypto API, runs in Edge Middleware)
 *
 * Both sign and verify with HS256 under the same JWT_SECRET. If the secret encoding or
 * the algorithm diverges between them, every user session would fail at the middleware
 * boundary — a silent, total authentication blackout.
 *
 * These tests catch that regression before it reaches production.
 */

// JWT_SECRET must be set before any jwt module is imported, because lib/jwt.ts
// reads the env at module load time and throws if it is missing.
process.env.JWT_SECRET = "test-secret-key-for-testing";

import { test } from "node:test";
import { ok, strictEqual, rejects } from "node:assert/strict";

// Define helper variables to hold the dynamically imported functions
let generateToken: typeof import("../lib/jwt").generateToken;
let validateToken: typeof import("../lib/jwt").validateToken;
let verifyJwtPayload: typeof import("../lib/auth/jwt-edge").verifyJwtPayload;

// Execute setup and import modules dynamically before running tests.
// This ensures process.env.JWT_SECRET is set before their module initialization.
const jwtPromise = (async () => {
  const jwt = await import("../lib/jwt");
  const jwtEdge = await import("../lib/auth/jwt-edge");
  generateToken = jwt.generateToken;
  validateToken = jwt.validateToken;
  verifyJwtPayload = jwtEdge.verifyJwtPayload;
})();

// ---------------------------------------------------------------------------
// generateToken (Node.js) → verifyJwtPayload (Edge) cross-compatibility
// ---------------------------------------------------------------------------

test("JWT cross-runtime compatibility — Node generates, Edge verifies", async (t) => {
  await jwtPromise;
  await t.test("Edge runtime accepts a token generated by the Node runtime", async () => {
    const payload = { sub: "user-42", role: "admin" };
    const token = await generateToken(payload);

    const decoded = await verifyJwtPayload(token);

    ok(decoded !== null, "verifyJwtPayload returned null — incompatible implementations");
    strictEqual(decoded!.sub, "user-42");
    strictEqual(decoded!.role, "admin");
  });

  await t.test("decoded payload preserves all custom claims", async () => {
    const token = await generateToken({ sub: "user-99", role: "user", extra: "data" });
    const decoded = await verifyJwtPayload(token);

    ok(decoded !== null);
    strictEqual(decoded!.sub, "user-99");
    strictEqual(decoded!.role, "user");
    strictEqual(decoded!.extra, "data");
  });

  await t.test("exp claim is present and set in the future", async () => {
    const token = await generateToken({ sub: "user-1" });
    const decoded = await verifyJwtPayload(token);

    ok(decoded !== null);
    ok(typeof decoded!.exp === "number");
    ok(decoded!.exp! > Math.floor(Date.now() / 1000), "Token is already expired at creation");
  });
});

// ---------------------------------------------------------------------------
// validateToken (Node.js) self-consistency
// ---------------------------------------------------------------------------

test("validateToken (Node runtime) — round-trip self-validation", async (t) => {
  await jwtPromise;
  await t.test("validates a token it generated", async () => {
    const token = await generateToken({ sub: "user-5", role: "content_manager" });
    const decoded = await validateToken(token) as { sub: string; role: string };

    strictEqual(decoded.sub, "user-5");
    strictEqual(decoded.role, "content_manager");
  });

  await t.test("rejects a token signed with a different secret", async () => {
    // Craft a raw token signed with a wrong secret via jsonwebtoken directly.
    const jwt = await import("jsonwebtoken");
    const impostor = jwt.default.sign({ sub: "attacker" }, "wrong-secret", { expiresIn: 3600 });

    await rejects(
      () => validateToken(impostor),
      (err: Error) => err.name === "JsonWebTokenError",
    );
  });

  await t.test("rejects a token with a tampered payload segment", async () => {
    const token = await generateToken({ sub: "user-1" });
    const [header, , signature] = token.split(".");

    // Replace the payload with an attacker-controlled one (base64url of {"sub":"admin"})
    const tamperedPayload = Buffer.from(JSON.stringify({ sub: "admin" })).toString("base64url");
    const tamperedToken = `${header}.${tamperedPayload}.${signature}`;

    await rejects(
      () => validateToken(tamperedToken),
      (err: Error) => err.name === "JsonWebTokenError",
    );
  });

  await t.test("rejects an expired token", async () => {
    // Generate a token that is already expired (e.g. -10 seconds)
    const jwt = await import("jsonwebtoken");
    const secret = process.env.JWT_SECRET!;
    const expired = jwt.default.sign(
      { sub: "user-expired", exp: Math.floor(Date.now() / 1000) - 10 },
      secret,
    );

    await rejects(
      () => validateToken(expired),
      (err: Error) => err.name === "TokenExpiredError",
    );
  });
});

// ---------------------------------------------------------------------------
// Edge verifyJwtPayload — token rejection behaviour
// ---------------------------------------------------------------------------

test("verifyJwtPayload (Edge runtime) — rejects invalid tokens", async (t) => {
  await jwtPromise;
  await t.test("returns null for an expired token", async () => {
    // Generate a token that expires immediately (1 second in the past).
    // We use jsonwebtoken directly to control the exact exp value.
    const jwt = await import("jsonwebtoken");
    const secret = process.env.JWT_SECRET!;

    const expired = jwt.default.sign(
      { sub: "user-expired", exp: Math.floor(Date.now() / 1000) - 10 },
      secret,
    );

    const decoded = await verifyJwtPayload(expired);
    strictEqual(decoded, null, "verifyJwtPayload should return null for an expired token");
  });

  await t.test("returns null for a completely malformed token", async () => {
    const result = await verifyJwtPayload("this.is.not.a.jwt");
    strictEqual(result, null);
  });

  await t.test("returns null for an empty string", async () => {
    const result = await verifyJwtPayload("");
    strictEqual(result, null);
  });

  await t.test("returns null for a token with only two segments", async () => {
    const result = await verifyJwtPayload("header.payload");
    strictEqual(result, null);
  });

  await t.test("returns null for a token signed with a wrong secret", async () => {
    const jwt = await import("jsonwebtoken");
    const impostor = jwt.default.sign({ sub: "attacker" }, "wrong-secret", { expiresIn: 3600 });

    const result = await verifyJwtPayload(impostor);
    strictEqual(result, null, "Edge verifier should reject tokens from a different secret");
  });
});
